### ISSUE TITLE
User able to alter weight of block in region via configure with move disabled

### ISSUE THREAD

**Issue by mnods** [catalyst/moodle_tool_blocksmanager#12]
found in testing with locking functionality:
 
Scenario 1: Side pre region locked in one category. No block rules applied. (FR05) and 
Region rules:
Configure Y
Delete N
Hide Y
Add N
Move N
 
Scenario 3: individual block rules applied for selected blocks in units in a category. No region locking applied (FR04)

Block rules:
side-pre, news-items configure Y delete N hide Y move N
side-pre, calendar_upcoming configure Y delete N hide Y move N

in a course have a number of other blocks present in side-pre
as manager user in course without bypass cap, hit configure and alter weight of block on this page, block is moved to new order position.

Assumption was that manager role without bypass capability would not be able to move any block in side-pre in any way.

D&D is disabled as expected
while configure is enabled the user is able to alter the region but on save an error message is displayed (as expected)
while configure is enabled the user is able to alter the weight in “on this page” so is able to change position of blocks
 
ideally with these rules no movement should be possible.

**Comment by tuanngocnguyen** [comment]
Hi @mnods , 

I have fixed this issue

**Comment by mnods** [comment]
excellent - thanks
