### ISSUE TITLE
issue with multiblock plugin

### ISSUE THREAD

**Issue by mnods** [catalyst/moodle_tool_blocksmanager#18]
More an FYI as i was trying out multiblock, which looks very useful.

I understand multiblock was also developed by catalyst, but blocks manager has a problem with it. 
https://github.com/Arantor/moodle-block_multiblock

in mdl 3.9
Exception - Argument 2 passed to tool_blocksmanager\locking_manager::can_move() must be of the type string, null given, called in [dirroot]/admin/tool/blocksmanager/classes/block_manager.php on line 367

when adding a block to a multiblock, in my case on the dashboard.
cheers

**Comment by MURBASLMS** [comment]
Hi, i see you made a comment on multiblock repo, suggesting perhaps had been resolved but fyi still errors with block manager in latest 3.11. 

```
Exception - Argument 2 passed to tool_blocksmanager\locking_manager::can_move() must be of the type string, null given, called in [dirroot]/admin/tool/blocksmanager/classes/block_manager.php on line 366
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 112 of /admin/tool/blocksmanager/classes/locking_manager.php: TypeError thrown
line 366 of /admin/tool/blocksmanager/classes/block_manager.php: call to tool_blocksmanager\locking_manager->can_move()
line 253 of /blocks/moodleblock.class.php: call to tool_blocksmanager\block_manager->edit_controls()
line 173 of /blocks/multiblock/block_multiblock.php: call to block_base->get_content_for_output()
line 341 of /blocks/moodleblock.class.php: call to block_multiblock->get_content()
line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 221 of /blocks/multiblock/block_multiblock.php: call to block_base->get_content_for_output()
line 1181 of /lib/blocklib.php: call to block_multiblock->get_content_for_output()
line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 4004 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 46 of /theme/fordson/layout/course.php: call to core_renderer->blocks()
line 1401 of /lib/outputrenderers.php: call to include()
line 1331 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 245 of /course/view.php: call to core_renderer->header()
```

**Comment by danmarsden** [comment]
yeah - was an accidental button press (closing) - you might see I re-opened it straight after... I do have someone looking at this to see if it's an easy fix - hopefully update next week all going well..

**Comment by MURBASLMS** [comment]
yeah i saw, no worries, thanks, hope so as multiblock looks useful!

**Comment by uzimike** [comment]
I've made a [PR](https://github.com/catalyst/moodle_tool_blocksmanager/pull/26) for a potential fix. It works for me but would be worth reviewing

**Comment by sarahjcotton** [comment]
Hello, is the PR for this issue likely to be merged any time soon? We have a client using the multiblock plugin who wishes to be able to use the blocksmanager but is running into the same issue.

I've applied the patch for now which seems to be doing the job, so thank you for that @uzimike :)

**Comment by danmarsden** [comment]
Thanks - I've just merged that in now - (just got back from leave.)
