### ISSUE TITLE
exclude dashboard regions from locking

### ISSUE THREAD

**Issue by mnods** [catalyst/moodle_tool_blocksmanager#8]
locking of regions affects dashboard side-pre region.

with side-pre locked in blockmanager tool

Adding a new html block to dashboard default page side-pre or a personal dashboard side-pre results in the locking error.

Another scenario: present html block on dashboard for all users (via frontpage > display throughout site > on dashboard > set to show on dashboard (side-pre is only available region for dashboard in theme.)

on frontpage, html block set to show throughout site, can choose regions other than side-pre, if side-pre chosen then error message is presented - this is expected in relation to courses but dashboard side-pre should allow (i think.)

note: I know default dashboard + reset for all users is possible but this has never worked in our environment (many users, reset hangs/times out), though we have only recently started using the dashboard (students have always been directed to course sites from a portal, staff now go direct to dashboard.) 

I have seen https://github.com/catalyst/moodle-local_reset_dashboard is related to this and have given it a go but it still takes a long time, not had any sucess yet. Is using default dashboard the way to go for managing consistent dashboard blocks?

**Comment by mnods** [comment]
i can see your reset_dashboard script works well, took a long time first run but now works straight away and that this would be the way to go with managing dashboard. side note: when setting default dashboard, then resetting, user's dashboard doesn't appear to respect ordering.

so the key issue is dashboard regions should be excluded from locking, or an option to include/exclude would be needed.

**Comment by dmitriim** [comment]
In a new version of the locking functionality dashboard is excluded. We lock blocks just for course related pages,
